/* ══════════════════════════════════════════
   DATA — Jesse Itzler発音データ
   ws = 動画currentTime基準（秒）
   ローカルファイルの開始位置がYouTube t=394s と異なる場合
   はオフセットスライダーで補正
══════════════════════════════════════════ */
const PARAS = [
  {
    id:0, start:0.0, end:8.8,
    en:"If you can't organize your life into eight simple boxes, you're probably not organized and you're probably not operating efficiently.",
    ja:"もし自分の人生を8つのシンプルなボックスに整理できないとしたら、あなたはおそらく整理整頓ができていないし、効率的に動けてもいないでしょう。",
    words:[
      {t:"If",           ws:0.15, stress:"w", elision:true,  inton:null,   note:"ɪf→əf (reduced)"},
      {t:"you",          ws:0.35, stress:"w", elision:false, inton:null,   note:"juː→jə"},
      {t:"can't",        ws:0.55, stress:"s", elision:false, inton:"rise", note:"kænt — t-drop"},
      {t:"organize",     ws:1.05, stress:"s", elision:false, inton:"rise", syl:"or·ga·nize", note:"ˈɔːɡənaɪz"},
      {t:"your",         ws:1.9,  stress:"w", elision:true,  inton:null,   note:"jʊr→jər"},
      {t:"life",         ws:2.2,  stress:"s", elision:false, inton:null},
      {t:"into",         ws:2.55, stress:"w", elision:true,  inton:null,   note:"ˈɪntʊ→ˈɪnə (t-flap)"},
      {t:"eight",        ws:2.95, stress:"s", elision:false, inton:"rise"},
      {t:"simple",       ws:3.35, stress:"s", elision:false, inton:null,   syl:"sim·ple"},
      {t:"boxes,",       ws:3.85, stress:"s", elision:false, inton:"fall"},
      {t:"you're",       ws:4.55, stress:"w", elision:true,  inton:null,   note:"jʊr→jər"},
      {t:"probably",     ws:4.8,  stress:"s", elision:true,  inton:null,   note:"ˈprɒbəbli→ˈprɒbli"},
      {t:"not",          ws:5.25, stress:"s", elision:false, inton:null},
      {t:"organized",    ws:5.55, stress:"s", elision:false, inton:null,   syl:"or·ga·nized"},
      {t:"and",          ws:6.2,  stress:"w", elision:true,  inton:null,   note:"ænd→ən"},
      {t:"you're",       ws:6.45, stress:"w", elision:true,  inton:null,   note:"jʊr→jər"},
      {t:"probably",     ws:6.65, stress:"s", elision:true,  inton:null,   note:"ˈprɒbli"},
      {t:"not",          ws:7.1,  stress:"s", elision:false, inton:null},
      {t:"operating",    ws:7.4,  stress:"s", elision:false, inton:"rise", syl:"op·er·at·ing"},
      {t:"efficiently.", ws:8.1,  stress:"s", elision:false, inton:"fall", syl:"ef·fi·cient·ly"},
    ]
  },
  {
    id:1, start:8.8, end:14.5,
    en:"And I'm going to show you how to plan yours right now.",
    ja:"今から、その計画をどう立てればいいのかをお見せします。",
    words:[
      {t:"And",   ws:8.85, stress:"w", elision:true,  inton:null,   note:"ænd→ən"},
      {t:"I'm",   ws:9.1,  stress:"w", elision:false, inton:null},
      {t:"going", ws:9.35, stress:"s", elision:false, inton:null},
      {t:"to",    ws:9.75, stress:"w", elision:true,  inton:null,   note:"going to→ˈɡʌnə"},
      {t:"show",  ws:9.95, stress:"s", elision:false, inton:"rise"},
      {t:"you",   ws:10.3, stress:"w", elision:false, inton:null,   note:"juː→jə"},
      {t:"how",   ws:10.55,stress:"s", elision:false, inton:null},
      {t:"to",    ws:10.85,stress:"w", elision:true,  inton:null,   note:"tʊ→tə"},
      {t:"plan",  ws:11.05,stress:"s", elision:false, inton:"rise"},
      {t:"yours", ws:11.5, stress:"s", elision:false, inton:null},
      {t:"right", ws:11.9, stress:"s", elision:false, inton:"rise"},
      {t:"now.",  ws:12.35,stress:"s", elision:false, inton:"fall"},
    ]
  },
  {
    id:2, start:14.5, end:41.0,
    en:"So pull out a piece of looseleaf paper, just a blank piece of paper, and make eight boxes and then think about the buckets that matter the most in your life.",
    ja:"ルーズリーフでも何でもいいので、白紙を1枚用意して8つのボックスを作ってください。それから、あなたの人生で最も重要な「バケツ（カテゴリー）」について考えてみるんです。",
    words:[
      {t:"So",        ws:14.55,stress:"w", elision:false, inton:null},
      {t:"pull",      ws:15.0, stress:"s", elision:false, inton:"rise"},
      {t:"out",       ws:15.45,stress:"s", elision:true,  inton:null,   note:"aʊt→aʊɾ (flap)"},
      {t:"a",         ws:15.75,stress:"w", elision:true,  inton:null,   note:"eɪ→ə"},
      {t:"piece",     ws:15.95,stress:"s", elision:false, inton:null},
      {t:"of",        ws:16.3, stress:"w", elision:true,  inton:null,   note:"ɒv→əv"},
      {t:"looseleaf", ws:16.55,stress:"s", elision:false, inton:"rise", syl:"loose·leaf"},
      {t:"paper,",    ws:17.3, stress:"s", elision:false, inton:"fall"},
      {t:"just",      ws:18.1, stress:"s", elision:false, inton:null},
      {t:"a",         ws:18.5, stress:"w", elision:true,  inton:null},
      {t:"blank",     ws:18.7, stress:"s", elision:false, inton:"rise"},
      {t:"piece",     ws:19.15,stress:"s", elision:false, inton:null},
      {t:"of",        ws:19.45,stress:"w", elision:true,  inton:null},
      {t:"paper,",    ws:19.65,stress:"s", elision:false, inton:"fall"},
      {t:"and",       ws:20.3, stress:"w", elision:true,  inton:null,   note:"ænd→ən"},
      {t:"make",      ws:20.6, stress:"s", elision:false, inton:"rise"},
      {t:"eight",     ws:21.1, stress:"s", elision:false, inton:null},
      {t:"boxes",     ws:21.55,stress:"s", elision:false, inton:null},
      {t:"and",       ws:22.1, stress:"w", elision:true,  inton:null},
      {t:"then",      ws:22.35,stress:"s", elision:false, inton:null},
      {t:"think",     ws:22.75,stress:"s", elision:false, inton:"rise"},
      {t:"about",     ws:23.2, stress:"w", elision:false, inton:null,   note:"t-drop"},
      {t:"the",       ws:23.6, stress:"w", elision:true,  inton:null},
      {t:"buckets",   ws:23.8, stress:"s", elision:false, inton:"rise"},
      {t:"that",      ws:24.4, stress:"w", elision:true,  inton:null,   note:"ðæt→ðət"},
      {t:"matter",    ws:24.65,stress:"s", elision:false, inton:null,   note:"ˈmæɾər (t-flap)"},
      {t:"the",       ws:25.2, stress:"w", elision:true,  inton:null},
      {t:"most",      ws:25.4, stress:"s", elision:false, inton:null},
      {t:"in",        ws:25.85,stress:"w", elision:true,  inton:null},
      {t:"your",      ws:26.05,stress:"w", elision:true,  inton:null,   note:"jʊr→jər"},
      {t:"life.",     ws:26.3, stress:"s", elision:false, inton:"fall"},
    ]
  },
  {
    id:3, start:41.0, end:60.0,
    en:"So for me, it was adventure — that's a huge part of my life — business, my marriage, financial, my health, my kids, my personal, and charity.",
    ja:"私の場合、それは「冒険（人生の大きな割合）」「ビジネス」「結婚生活」「財務」「健康」「子供たち」「個人」「チャリティ」でした。",
    words:[
      {t:"So",         ws:41.05,stress:"w", elision:false, inton:null},
      {t:"for",        ws:41.5, stress:"w", elision:true,  inton:null,   note:"fɔːr→fər"},
      {t:"me,",        ws:41.75,stress:"s", elision:false, inton:"fall"},
      {t:"it",         ws:42.4, stress:"w", elision:false, inton:null},
      {t:"was",        ws:42.65,stress:"w", elision:true,  inton:null,   note:"wɒz→wəz"},
      {t:"adventure",  ws:42.9, stress:"s", elision:false, inton:"rise", syl:"ad·ven·ture", note:"ədˈvɛntʃər"},
      {t:"—",          ws:44.2, stress:"w", elision:false, inton:null},
      {t:"that's",     ws:44.4, stress:"w", elision:false, inton:null},
      {t:"a",          ws:44.7, stress:"w", elision:true,  inton:null},
      {t:"huge",       ws:44.9, stress:"s", elision:false, inton:"rise"},
      {t:"part",       ws:45.3, stress:"s", elision:false, inton:null},
      {t:"of",         ws:45.6, stress:"w", elision:true,  inton:null},
      {t:"my",         ws:45.8, stress:"w", elision:false, inton:null},
      {t:"life",       ws:46.0, stress:"s", elision:false, inton:"fall"},
      {t:"—",          ws:46.7, stress:"w", elision:false, inton:null},
      {t:"business,",  ws:47.1, stress:"s", elision:false, inton:"rise", syl:"biz·ness"},
      {t:"my",         ws:47.95,stress:"w", elision:false, inton:null},
      {t:"marriage,",  ws:48.2, stress:"s", elision:false, inton:"rise", syl:"mar·riage"},
      {t:"financial,", ws:49.1, stress:"s", elision:false, inton:"rise", syl:"fi·nan·cial"},
      {t:"my",         ws:50.15,stress:"w", elision:false, inton:null},
      {t:"health,",    ws:50.4, stress:"s", elision:false, inton:"rise"},
      {t:"my",         ws:51.1, stress:"w", elision:false, inton:null},
      {t:"kids,",      ws:51.35,stress:"s", elision:false, inton:"rise"},
      {t:"my",         ws:52.0, stress:"w", elision:false, inton:null},
      {t:"personal,",  ws:52.25,stress:"s", elision:false, inton:"rise"},
      {t:"and",        ws:53.1, stress:"w", elision:true,  inton:null,   note:"ænd→ən"},
      {t:"charity.",   ws:53.4, stress:"s", elision:false, inton:"fall"},
    ]
  },
  {
    id:4, start:60.0, end:80.0,
    en:"I found that, you know, when you write down your goals, you're way more likely to achieve them.",
    ja:"目標を紙に書くと、達成できる確率が格段に上がることに気づきました。",
    words:[
      {t:"I",        ws:60.1, stress:"w", elision:false, inton:null},
      {t:"found",    ws:60.4, stress:"s", elision:false, inton:null},
      {t:"that,",    ws:60.85,stress:"w", elision:true,  inton:null,   note:"ðæt→ðət"},
      {t:"you",      ws:61.2, stress:"w", elision:false, inton:null},
      {t:"know,",    ws:61.45,stress:"s", elision:false, inton:"fall"},
      {t:"when",     ws:62.0, stress:"s", elision:false, inton:null},
      {t:"you",      ws:62.35,stress:"w", elision:false, inton:null},
      {t:"write",    ws:62.6, stress:"s", elision:false, inton:"rise"},
      {t:"down",     ws:63.1, stress:"s", elision:false, inton:null},
      {t:"your",     ws:63.5, stress:"w", elision:true,  inton:null,   note:"jʊr→jər"},
      {t:"goals,",   ws:63.75,stress:"s", elision:false, inton:"fall"},
      {t:"you're",   ws:64.55,stress:"w", elision:true,  inton:null,   note:"jʊr→jər"},
      {t:"way",      ws:64.85,stress:"s", elision:false, inton:"rise"},
      {t:"more",     ws:65.3, stress:"s", elision:false, inton:null},
      {t:"likely",   ws:65.7, stress:"s", elision:false, inton:null},
      {t:"to",       ws:66.2, stress:"w", elision:true,  inton:null,   note:"tʊ→tə"},
      {t:"achieve",  ws:66.45,stress:"s", elision:false, inton:"rise"},
      {t:"them.",    ws:67.1, stress:"w", elision:false, inton:"fall",  note:"ðɛm→ðəm"},
    ]
  },
  {
    id:5, start:80.0, end:120.0,
    en:"This is also a permission sheet to say no to things. Because if it's not moving the needle in one of these buckets, that's a good indicator that you probably shouldn't be doing it.",
    ja:"また、これは物事に「ノー」と言うための「許可証」でもあります。バケツのどれかを前進させないなら「やるべきではない」というサインです。",
    words:[
      {t:"This",       ws:80.15, stress:"s", elision:false, inton:null},
      {t:"is",         ws:80.55, stress:"w", elision:true,  inton:null,   note:"ɪz→əz"},
      {t:"also",       ws:80.85, stress:"s", elision:false, inton:null},
      {t:"a",          ws:81.4,  stress:"w", elision:true,  inton:null},
      {t:"permission", ws:81.65, stress:"s", elision:false, inton:"rise", syl:"per·mis·sion"},
      {t:"sheet",      ws:82.5,  stress:"s", elision:false, inton:null},
      {t:"to",         ws:82.9,  stress:"w", elision:true,  inton:null},
      {t:"say",        ws:83.1,  stress:"s", elision:false, inton:"rise"},
      {t:"no",         ws:83.55, stress:"s", elision:false, inton:"fall"},
      {t:"to",         ws:83.95, stress:"w", elision:true,  inton:null},
      {t:"things.",    ws:84.2,  stress:"s", elision:false, inton:"fall"},
      {t:"Because",    ws:85.2,  stress:"w", elision:false, inton:null,   syl:"be·cause"},
      {t:"if",         ws:85.7,  stress:"w", elision:false, inton:null},
      {t:"it's",       ws:85.95, stress:"w", elision:true,  inton:null},
      {t:"not",        ws:86.25, stress:"s", elision:false, inton:null},
      {t:"moving",     ws:86.6,  stress:"s", elision:false, inton:"rise"},
      {t:"the",        ws:87.2,  stress:"w", elision:true,  inton:null},
      {t:"needle",     ws:87.4,  stress:"s", elision:false, inton:null},
      {t:"in",         ws:87.95, stress:"w", elision:true,  inton:null},
      {t:"one",        ws:88.2,  stress:"w", elision:false, inton:null},
      {t:"of",         ws:88.5,  stress:"w", elision:true,  inton:null},
      {t:"these",      ws:88.7,  stress:"w", elision:false, inton:null},
      {t:"buckets,",   ws:88.95, stress:"s", elision:false, inton:"fall"},
      {t:"that's",     ws:89.85, stress:"w", elision:false, inton:null},
      {t:"a",          ws:90.15, stress:"w", elision:true,  inton:null},
      {t:"good",       ws:90.35, stress:"s", elision:false, inton:"rise"},
      {t:"indicator",  ws:90.8,  stress:"s", elision:false, inton:null,   syl:"in·di·ca·tor"},
      {t:"that",       ws:91.7,  stress:"w", elision:true,  inton:null},
      {t:"you",        ws:92.0,  stress:"w", elision:false, inton:null},
      {t:"probably",   ws:92.25, stress:"s", elision:true,  inton:null,   note:"ˈprɒbli"},
      {t:"shouldn't",  ws:92.75, stress:"s", elision:false, inton:"rise"},
      {t:"be",         ws:93.35, stress:"w", elision:false, inton:null},
      {t:"doing",      ws:93.6,  stress:"s", elision:false, inton:null},
      {t:"it.",        ws:94.1,  stress:"w", elision:false, inton:"fall"},
    ]
  },
];
window.PARAS = PARAS;

